[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

# Configuração para definir a versão do Node.js
[build.environment]
  NODE_VERSION = "18.17.1"

# Redirecionamento de todas as rotas para /index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirecionamento para a API no Google Cloud Functions
[[redirects]]
  from = "/api/*"
  to = "https://us-central1-projeto-arch-lambda-439723.cloudfunctions.net/function-1/:splat"
  status = 200
  force = true
